$memory = 1025
$cpus = 1
$mongo_port = 27017
$mongo_host = "193.168.1.2"

Vagrant.configure("2") do |config|
  ## Choose your base box
  config.vm.box = "hashicorp/precise64"
  config.vm.hostname = "dev.beerhunter.pl"
  config.vm.network "private_network", ip:  $mongo_host

  config.vm.provider "virtualbox" do |v|
    v.memory = $memory
    v.cpus = $cpus
    v.gui = false
  end

  ## For masterless, mount your file roots file root
  config.vm.synced_folder "salt/roots/", "/srv/"
  config.vm.network :forwarded_port, guest: $mongo_port, host: $mongo_port

  ## Set your salt configs here
  config.vm.provision :salt do |salt|

    ## Minion config is set to ``file_client: local`` for masterless
    salt.minion_config = "salt/minion_vagrant"

    ## Installs our example formula in "salt/roots/salt"
    salt.run_highstate = true

    #export port and ip for mongodb server
    salt.pillar({
      "mongodb" => {
        "settings" => {
          "port" => $mongo_port,
          "bind_ip" => $mongo_host
        }
      }
    })

  end

end

