#!/bin/bash
NAME=perly
docker build -t $NAME .
IS_RUNNING=$(docker ps |grep $NAME | wc -l)
echo "IS_RUNNING is $IS_RUNNING"

if [ "$IS_RUNNING" -gt "0" ]; then
        echo "$NAME is running now. removing..."
        docker stop $NAME
        docker rm -f  $NAME
fi

export PERLY_CONT=$(docker run   --link mongodb:mongodb  --name $NAME  $NAME carton exec "perl RateBeerMaster.pl --mongourl="mongodb"" )
echo "started $NAME container. container id is $PERLY_CONT"
